FROM python:3.11-bullseye

RUN pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
RUN pip install ninja
RUN pip install "git+https://github.com/facebookresearch/pytorch3d.git"

#RUN pip install -U openmim
#RUN mim install 'mmcv-full==1.7.1'

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .
RUN pip install -e .
