class Graph:
    def add(self, filter, args=None, **kwargs) -> FilterContext: ...
    def add_buffer(self, template=None, width=None, height=None, format=None,
                   name=None, time_base=None) -> FilterContext: ...
    def configure(self, auto_buffer=True, force=False): ...
    def push(self, frame): ...
    def pull(self): ...

class FilterContext: ...
