name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: x64
          cache: 'pip' # caching pip dependencies
      - name: Install Dependencies
        run: |
          set -eux
          pip install lintrunner lintrunner-adapters
          lintrunner init
      - name: Run Lint
        run: |
          set -eux

          lintrunner --skip PYRE --force-color --all-files
