name: Pyre

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pyre:
    strategy:
      matrix:
        platform: [ubuntu-22.04]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: Dockerfile.cpu
          tags: |
            ghcr.io/d4l3k/torchdrive:cpu
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Pyre
        run: docker run --rm ghcr.io/d4l3k/torchdrive:cpu pyre
