name: Python Unittests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unittest:
    strategy:
      matrix:
        python-version: ['3.10']
        platform: [ubuntu-20.04]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: |
          set -eux

          pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu
          pip install -r requirements.txt
          pip install -e .
      - name: Run tests
        run: pytest
      - name: Pyre
        run: pyre
