name: Python Unittests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unittest:
    strategy:
      matrix:
        python-version: [3.8, '3.10']
        platform: [ubuntu-22.04]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
      - name: NVIDIA Driver Install
        run: |
          sudo add-apt-repository -y ppa:graphics-drivers
          sudo apt-get update -qq
          sudo apt-get install -y nvidia-driver-440
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: |
          set -eux

          pip install --upgrade wheel pip
          pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116
          pip install -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py310_cu116_pyt1131/download.html pytorch3d
          pip install -U openmim
          mim install mmcv-full
          pip install -r requirements.txt
          pip install -e .
      - name: Run tests
        run: pytest
